---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: deploy-action
run-name: Deploy of ${{ inputs.deployment_version }}
on:
  workflow_dispatch:
    inputs:
      deployment_version:
        description: the image tag to deploy
        required: true
        type: string
jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment:
      name: "Development"
    steps:
      - run: echo "Deploying to Development"
  deploy-integration:
    name: Deploy to Integration
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: "Integration"
    steps:
      - run: echo "Deploying to Integration"
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-integration
    environment:
      name: "Production"
    steps:
      - run: echo "Deploying to Production"